spring:
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
      repositories:
        enabled: false
  main:
    web-application-type: reactive

rqueue:
  reactive:
    enabled: true
  system:
    mode: both
  job:
    enabled: false
    durability:
      in-terminal-state: 0
  message:
    durability:
      in-terminal-state: 0